apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use the base eso-beyondtrust component
# The BeyondTrust server config is shared across clusters
resources:
  - ../../../../components/eso-beyondtrust
