projects:

  cluster-config:
    annotations:
      notifications.argoproj.io/subscribe.on-sync-failed.slack: cluster-gitops
      notifications.argoproj.io/subscribe.on-health-degraded.slack: cluster-gitops
    description: Project for overall cluster configuration
    namespace: openshift-gitops
    sourceRepos:
    - https://github.com/rich-p-ai/argo-demo.git
    - https://github.com/rich-p-ai/argo-apps-demo.git
    destinations: |
      - namespace: '*'
        server: '*'
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'

# Common applications are defined here
# Each cluster can override or add additional applications in their values.yaml
applications:

  cluster-admin-group:
    annotations:
      argocd.argoproj.io/sync-wave: '1'
    destination:
      namespace: openshift-config
    source:
      path: groups/all/overlays/cluster-admin-group
      targetRevision: main

  node-health-check-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-node-healthcheck-operator
    source:
      path: groups/all/overlays/node-health-check-operator

  mtv-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-mtv
    source:
      path: groups/all/overlays/mtv-operator

  netapp-trident-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: trident
    source:
      path: groups/all/overlays/netapp-trident-operator