apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/aap-configuration

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: rosa-ansible-controller
      - op: add
        path: /spec/public_base_url
        value: "https://rosa-ansible-aap.apps.rosa.rosa.m34m.p3.openshiftapps.com"
    target:
      kind: AutomationController
      name: automation-controller
