apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/mtv-configuration/

# Customize MTV configuration for hub cluster
patches:
  - patch: |-
      - op: replace
        path: /spec/controller_max_vm_inflight
        value: 20
    target:
      kind: ForkliftController
      name: forklift-controller
