# CT1 Cluster Configuration
# This cluster is managed from hub ArgoCD

default:
  app:
    labels:
      app-source: cluster-ct1
      repo: cluster-config
    destination:
      server: https://api.ct1.thir.p3.openshiftapps.com:443
    source:
      repoURL: https://github.com/rich-p-ai/argo-demo.git
      targetRevision: HEAD

applications:
  # Cert-manager for ct1 cluster
  ct1-cert-manager-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: cert-manager
      server: https://api.ct1.thir.p3.openshiftapps.com:443
    source:
      path: components/cert-manager-operator
      repoURL: https://github.com/rich-p-ai/argo-demo.git

  # Add ct1-specific applications below:

