apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: site-to-site-vpn:apps/Deployment:site-to-site-vpn/site-to-site-vpn
    deployment.kubernetes.io/revision: "1"
    description: Site-to-Site VPN client connecting to AWS Transit Gateway
  creationTimestamp: "2026-02-04T16:36:04Z"
  generation: 1
  labels:
    app: site-to-site-vpn
    app.kubernetes.io/component: vpn-client
    app.kubernetes.io/name: site-to-site-vpn
  name: site-to-site-vpn
  namespace: site-to-site-vpn
  resourceVersion: "1389465"
  uid: 2923c26d-be62-4b22-a99c-63ac91ad957c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: site-to-site-vpn
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: site-to-site-vpn
        app.kubernetes.io/component: vpn-client
        app.kubernetes.io/name: site-to-site-vpn
    spec:
      containers:
      - command:
        - /bin/bash
        - /etc/ipsec-config/start-vpn.sh
        image: registry.access.redhat.com/ubi9/ubi:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep -q '[c]haron'
          failureThreshold: 5
          initialDelaySeconds: 180
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        name: strongswan
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep -q '[c]haron'
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_ADMIN
            - NET_RAW
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ipsec-config
          name: ipsec-config
          readOnly: true
        - mountPath: /etc/vpn-certs
          name: vpn-certs
          readOnly: true
        - mountPath: /run
          name: run
        - mountPath: /var/run
          name: var-run
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: site-to-site-vpn
      serviceAccountName: site-to-site-vpn
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/unschedulable
        operator: Exists
      volumes:
      - configMap:
          defaultMode: 493
          name: ipsec-config
        name: ipsec-config
      - name: vpn-certs
        secret:
          defaultMode: 384
          secretName: vpn-certificates
      - emptyDir: {}
        name: run
      - emptyDir: {}
        name: var-run
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-02-05T14:08:38Z"
    lastUpdateTime: "2026-02-05T14:11:07Z"
    message: ReplicaSet "site-to-site-vpn-cf45cc4d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2026-02-05T15:13:05Z"
    lastUpdateTime: "2026-02-05T15:13:05Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
