apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: site-to-site-vpn

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - deployment.yaml
  # NOTE: secret-template.yaml is NOT included - create secret manually with actual credentials
