apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: site-to-site-vpn

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - deployment.yaml
  # ExternalSecret to sync VPN certificates from AWS Secrets Manager
  - externalsecret-vpn-certs.yaml
  # NOTE: secret-template.yaml is NOT included - secret managed by ESO from AWS Secrets Manager
