apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../groups/all

resources:
  - ct1-root-application.yaml
  - demo-apps-root-application.yaml

helmGlobals:
  chartHome: ../../.helm/charts

helmCharts:
- name: argocd-app-of-app
  valuesFile: values.yaml
  namespace: openshift-gitops

patches: [] 