# Hub Cluster Configuration

default:
  app:
    labels:
      app-source: cluster-hub
      repo: cluster-config
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/rich-p-ai/argo-demo.git
      targetRevision: HEAD

applications:

  cert-manager-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: cert-manager
    source:
      path: components/cert-manager-operator

  external-secrets-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: external-secrets
    source:
      path: components/external-secrets-operator

  eso-azure-keyvault:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '10'
    destination:
      namespace: external-secrets
    source:
      path: components/eso-azure-keyvault

  acm-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: open-cluster-management
    source:
      path: clusters/hub/acm-operator

  acm-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: open-cluster-management
    source:
      path: clusters/hub/acm-configuration
