apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/aap-configuration

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: test-nonprod-controller
      - op: add
        path: /spec/public_base_url
        value: "https://test-nonprod-aap.apps.test-non-prod.<cluster-domain>.openshiftapps.com"
    target:
      kind: AutomationController
      name: automation-controller
