# MIA Cluster Configuration
# Add cluster-specific applications here

# Example:
# applications:
#
#   my-cluster-app:
#     annotations:
#       argocd.argoproj.io/compare-options: IgnoreExtraneous
#       argocd.argoproj.io/sync-wave: '15'
#     destination:
#       namespace: my-namespace
#     source:
#       path: clusters/mia/overlays/my-cluster-app
