applications:

  mtv-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '10'
    destination:
      namespace: openshift-mtv
    source:
      path: clusters/non-prod-west/overlays/mtv-configuration
